#!/bin/bash

# find /home/jorge/Documents/data/hst/ -type f -name "*_flc.fits"

files=(
    "/home/jorge/Documents/data/hst/Minni144/ifb444k0q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni144/ifb444kdq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni144/ifb444kbq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni144/ifb444juq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni144/ifb444jvq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni144/ifb444kiq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni147/ifb447lrq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni147/ifb447krq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni147/ifb447kqq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni147/ifb447ktq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni147/ifb447kvq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni147/ifb447loq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni146/ifb446bzq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni146/ifb446brq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni146/ifb446btq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni146/ifb446bvq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni146/ifb446bqq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni146/ifb446bxq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni324/ifb424rqq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni324/ifb424rmq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni324/ifb424roq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni324/ifb424rkq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni324/ifb424rsq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni324/ifb424rjq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni329/ifb429xwq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni329/ifb429xtq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni329/ifb429y0q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni329/ifb429y2q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni329/ifb429xuq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni329/ifb429xyq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni325/ifb425fnq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni325/ifb425feq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni325/ifb425fhq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni325/ifb425flq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni325/ifb425ffq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni325/ifb425fjq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni326/ifb426qkq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni326/ifb426qiq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni326/ifb426qcq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni326/ifb426qeq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni326/ifb426qgq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni326/ifb426qbq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni328/ifb428xnq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni328/ifb428xrq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni328/ifb428xpq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni328/ifb428xhq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni328/ifb428xkq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni328/ifb428xiq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni148/ifb448ejq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni148/ifb448e9q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni148/ifb448ebq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni148/ifb448e6q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni148/ifb448e7q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni148/ifb448emq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni145/ifb445koq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni145/ifb445kkq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni145/ifb445khq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni145/ifb445kwq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni145/ifb445kmq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni145/ifb445kiq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni330/ifb430f4q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni330/ifb430f8q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni330/ifb430f2q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni330/ifb430f1q_flc.fits"
    "/home/jorge/Documents/data/hst/Minni330/ifb430faq_flc.fits"
    "/home/jorge/Documents/data/hst/Minni330/ifb430f6q_flc.fits"
)


for file in "${files[@]}"
do
    echo "Processing: $file"
    python main.py -f "$file" --hmin 3 --fmin 10 --name "RunALL_hmin3fmin10" --description "20241231_allclusters"
    echo "-----------------------------"
done


